DROP TABLE USERS;
DROP TABLE GROUPS;
DROP TABLE GROUPS_USERS;



CREATE TABLE  GROUPS (GROUP_ID NUMBER(4) NOT NULL PRIMARY KEY,
GROUP_NAME VARCHAR2(10), 
GROUP_DESCRIPTION VARCHAR2(20));





CREATE TABLE USERS(USERS_LOGIN NUMBER(4) NOT NULL PRIMARY KEY, 
USER_PASSWORD VARCHAR2(10));






CREATE TABLE  GROUPS_USERS(USERS_LOGIN NUMBER(4) NOT NULL ,
GROUP_ID NUMBER(4) NOT NULL ,
CONSTRAINT PR_KEYS PRIMARY KEY(USERS_LOGIN,GROUP_ID),
FOREIGN KEY (USERS_LOGIN) REFERENCES USERS(USERS_LOGIN),
FOREIGN KEY( GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);
