DROP TABLE USERS;
DROP TABLE GROUPS;
DROP TABLE GROUPS_USERS;



CREATE TABLE  GROUPS (GROUP_ID NUMBER(4) NOT NULL PRIMARY KEY,
GROUP_NAME VARCHAR2(10), 
GROUP_DESCRIPTION VARCHAR2(20));





CREATE TABLE USERS(USER_ID NUMBER(4) NOT NULL PRIMARY KEY,
USER_LOGIN NUMBER(4)  , 
USER_PASSWORD VARCHAR2(10));






CREATE TABLE  GROUPS_USERS(USERS_ID NUMBER(4) NOT NULL ,
GROUP_ID NUMBER(4) NOT NULL ,
CONSTRAINT PR_KEYS PRIMARY KEY(USERS_ID,GROUP_ID),
FOREIGN KEY (USERS_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY( GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);
