DROP TABLE GROUPS_USERS;
DROP TABLE USERS;
DROP TABLE GROUPS;




CREATE TABLE  GROUPS (GROUP_ID NUMBER(4) NOT NULL PRIMARY KEY,
GROUP_NAME VARCHAR2(10), 
GROUP_DESCRIPTION VARCHAR2(20));





CREATE TABLE USERS(USER_ID NUMBER(4) NOT NULL PRIMARY KEY,
USER_LOGIN VARCHAR2(12)  , 
USER_PASSWORD VARCHAR2(12));






CREATE TABLE  GROUPS_USERS(USERS_ID NUMBER(4) NOT NULL ,
GROUP_ID NUMBER(4) NOT NULL ,
CONSTRAINT PR_KEYS PRIMARY KEY(USERS_ID,GROUP_ID),
FOREIGN KEY (USERS_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY( GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);

select * from users;
delete from users;